---
title: 'Solutions: R-Census-Data-Challenges'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, libraries}

# run this chunk if you have not loaded the necessary libraries yet. 
if (!require("pacman")) install.packages("pacman")

pacman::p_load(
  here, # locate files 
  tidyverse, # data wrangling
  sf,  # geospatial data management
  mapview, # mapping
  tigris, tidycensus  # census data 
)

# These six libraries should be loaded in your environment now. 

# Tigris options - used by tidycensus
# Cache retrieved geographic data locally
options(tigris_use_cache = TRUE)  
```


```{r, challenge_1A_solution}

## Fill in the code to fetch total population in 2010 just for California
get_decennial(geography = "state",   # census tabulation unit
              variables = "P001001", # variable(s) of interest
              year = 2010,           # census year
              state="CA")            # Filter by state is CA

```


```{r, challenge_1B_solution}

## fetch total pop in 2010 for CA, TX and FL
get_decennial(geography = "state",             # census tabulation unit
              variables = "P001001",           # variable(s) of interest
              year = 2010,                     # census year
              state=c("CA","FL","TX"))         # Filter by state is CA, Fl or TX

     
```



```{r, challenge_2A_solution}

## fetch 2010 population for Alameda & San Francisco Counties
get_decennial(geography = "county",              # census tabulation unit
              variables = "P001001",             # variable(s) of interest
              year = 2010,                       # census year
              state='CA',                        # filter by state 
              county=c('Alameda',
                       'San Francisco'))         # filter by County

```
```{r, challenge_2B_solution}

## Fill in the code to fetch total population in 2010 the US
get_decennial(geography = "us",   # census tabulation unit
              variables = "P001001", # variable(s) of interest
              year = 2010)           # census year

```

```{r, challenge_2C_solution}

## Fill in the code to fetch total population in 2010  census regions
get_decennial(geography = "region",   # census tabulation unit
              variables = "P001001", # variable(s) of interest
              year = 2010)           # census year
```

```{Variable Questions}
# Search vars2010
## vars20210 <- load_variables(2010, dataset='sf1', cache=T)

- `Median Age`: "P013001"

- `Average Family Size`: "P037001"

- `Number of occupied housing units` : "H003002"
```

```{r, challenge_3_solution}

# Fetch Avg family size by CA County in 2010
ca_fam_size <- get_decennial(geography='county',   # census tabulation unit
                            variables="P037001",   # variable(s) of interest
                            state='CA',            # filter by state, county,
                            year=2010)             # and year. 
                            

# create a ggplot
ca_fam_size %>%
  ggplot(aes(x = value, y = reorder(NAME, value))) + 
  geom_point()
  
# display the ggplot
ca_fam_size

```


```{r, challenge_4_solution}

# Load 2000 decennial census variables
vars2000 <- load_variables(year=2000, dataset = 'sf1', cache = T)

# Fetch Avg family size by CA County in 2000
ca_fam_size2000 <- get_decennial(geography='county',
                            variables='P033001',
                            state='CA',
                            year=2000)
  
```


```{r, challenge_5_solution}

## Fetch data + geometry for CA Median Age by county in 2010
ca_med_age <- get_decennial(geography = "county", 
                            variables = "P013001",
                            year = 2010, 
                            state='CA',
                            geometry=TRUE)

# map it with plot
plot(ca_med_age['value'])

# map it with ggplot - setting CRS to 3310
ca_med_age %>%
  ggplot(aes(fill = value)) + 
  geom_sf(color=NA) + 
  coord_sf(crs = 3310) + 
  scale_fill_viridis_c(option = "viridis") 

```

```{r, challenge_6_solution }

# Fetch the data
# Median household rent for San Francisco County
# using data from the ACS 2016—2020 5-year product.
sf_medrent <- get_acs(geography="tract",
                        variables=c(median_rent="B25064_001"),
                        year =2020,
                        state="CA",
                        county=c("San Francisco"),
                        geometry=T)

# Map it with plot - remove rows with NAs
plot(sf_medrent[!is.na(sf_medrent$estimate),]['estimate'])

# Map it with ggplot - remove rows with NAs
sf_medrent %>%
  drop_na(estimate)  %>%
  ggplot(aes(fill = estimate)) + 
  geom_sf(color=NA) + 
  coord_sf(crs = 26910) +  # CRS for Northern CA - UTM 10 
  scale_fill_viridis_c(option = "magma") 

```


```{r, challenge_7_solution }

# simple interactive map
mapview(sf_medrent)

# thematic (or choropleth) map of median rent
mapview(sf_medrent, zcol='estimate')

```

